# Generated by Django 2.2.3 on 2019-07-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_fee_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
