# Generated by Django 2.2.2 on 2019-06-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_image', models.ImageField(upload_to='images/')),
                ('sur_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('staff_designation', models.CharField(choices=[('Teacher', 'teacher'), ('Support Staff', 'Support Staff')], default='Teacher', max_length=20)),
            ],
            options={
                'ordering': ('sur_name', 'staff_designation'),
            },
        ),
    ]
