# Generated by Django 2.2.2 on 2019-06-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_staff', '0002_auto_20190619_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE'), ('undisclose', 'UNDISCLOSE')], max_length=10, null=True),
        ),
    ]
