# Generated by Django 2.2.2 on 2019-06-16 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('designated_fee', models.IntegerField()),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_staff.Staff')),
            ],
            options={
                'ordering': ('class_name', 'class_teacher'),
            },
        ),
    ]
