# Generated by Django 2.2.2 on 2019-06-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_layout',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
