# Generated by Django 2.2.2 on 2019-06-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0002_class_layout_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_layout',
            name='date_added',
            field=models.DateTimeField(blank=True),
        ),
    ]
